### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Skylion007** [anthony-martin/RifTop#2]
I would really appreciate some documentation about how the structure of this code is set up. Also some skeleton code that points the proper TODOs would be really helpful. I would love to try to work with you on this repository to finish implementing many of these features.

**Comment by anthony-martin** [comment]
Honestly this project is pretty much dead until such a point as very high resolution 3D goggles become available that support device sharing. Without more resolution and device sharing there is little use for this as envisioned. 
Dependency on hidden windows API methods also means that this process is possibly incompatible with future versions of windows.

Right now all the core features are in place but it does not have messaging support for all types of applications nor interaction with ribbon bars.
